inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  ExtraDetails: true
  TargetRubyVersion: 3.1.1
  TargetRailsVersion: 7.0.2.3
  Exclude:
    - 'bin/*'
    - 'db/**/**'
    - 'test/**/**'
    - 'spec/**/**'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Bundler/OrderedGems:
  Enabled: false

# === Layout ===

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/MultilineMethodCallBraceLayout:
  Enabled: true

Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: true

Layout/CaseIndentation:
  Enabled: true

Layout/CommentIndentation:
  Enabled: true

Layout/ElseAlignment:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/FirstParameterIndentation:
  Enabled: true

Layout/IndentationWidth:
  Width: 2
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal

Layout/LeadingCommentSpace:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceAroundKeyword:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeComma:
    Enabled: true

Layout/SpaceBeforeFirstArg:
    Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Layout/IndentationStyle:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable
  AutoCorrect: true

Lint/RequireParentheses:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

# === Style ===

Style/SymbolArray:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
  EnforcedStyle: always
  Exclude:
    - test/**/**
    - db/migrate/*

Style/DefWithParentheses:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: single_quotes

Style/RedundantReturn:
  Enabled: true
  AllowMultipleReturnValues: true

Style/Semicolon:
  Enabled: true
  AllowAsExpressionSeparator: true

Style/ColonMethodCall:
  Enabled: true

Style/HashSyntax:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/Next:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

# === Metrics ===

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

# === Lint ===

Lint/Debugger:
  Enabled: false

# === Naming ===

Naming/VariableNumber:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false