---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/csv":
    post:
      summary: Generate CSV
      tags:
      - CSV
      parameters: []
      responses:
        '201':
          description: csv generated
        '422':
          description: csv generated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                filename:
                  type: string
              required:
              - filename
  "/api/exams/{exam_id}/exam_requests":
    parameters:
    - name: Authorization
      in: header
      schema:
        type: string
    - name: exam_id
      in: path
      required: true
      schema:
        type: integer
    post:
      summary: Creates a exam request
      tags:
      - Exam Requests
      parameters: []
      responses:
        '201':
          description: created exam request
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                details:
                  type: string
                user_id:
                  type: integer
                updated_by_id:
                  type: integer
              required:
              - name
  "/api/exams/{exam_id}/exam_requests/{id}":
    parameters:
    - name: exam_id
      in: path
      required: true
      schema:
        type: integer
    - name: id
      in: path
      required: true
      schema:
        type: integer
    - name: Authorization
      in: header
      schema:
        type: string
    put:
      summary: Update Exam Request
      tags:
      - Exam Requests
      parameters: []
      responses:
        '200':
          description: updated exam request
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                details:
                  type: string
                user_id:
                  type: integer
                updated_by_id:
                  type: integer
    delete:
      summary: delete exam request
      tags:
      - Exam Requests
      responses:
        '200':
          description: deleted exam request
  "/api/exams":
    parameters:
    - name: Authorization
      in: header
      schema:
        type: string
    get:
      summary: Exam list
      tags:
      - Exams
      responses:
        '200':
          description: return exam list
    post:
      summary: Creates a exam
      tags:
      - Exams
      parameters: []
      responses:
        '201':
          description: created exam
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                starts_on:
                  type: string
                ends_on:
                  type: string
              required:
              - name
              - starts_on
              - ends_on
  "/api/exams/{id}":
    parameters:
    - name: Authorization
      in: header
      schema:
        type: string
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Retrieves a exam
      tags:
      - Exams
      responses:
        '200':
          description: Exam found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  starts_on:
                    type: string
                  ends_on:
                    type: string
        '404':
          description: exam not found
    put:
      summary: Update Exam
      tags:
      - Exams
      parameters: []
      responses:
        '200':
          description: updated exam
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                starts_on:
                  type: string
                ends_on:
                  type: string
    delete:
      summary: Delete Exam
      tags:
      - Exams
      responses:
        '200':
          description: deleted exam
  "/api/exams/{id}/completed":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    - name: Authorization
      in: header
      schema:
        type: string
    post:
      summary: Uncompleted exam
      tags:
      - Exams
      parameters: []
      responses:
        '200':
          description: uncompleted exam
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                completed:
                  type: boolean
  "/api/pdf":
    post:
      summary: Generate PDF
      tags:
      - PDF
      parameters: []
      responses:
        '201':
          description: pdf generated
        '422':
          description: error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                filename:
                  type: string
                template:
                  type: string
              required:
              - filename
  "/api/policies":
    parameters:
    - name: Authorization
      in: header
      schema:
        type: string
    get:
      summary: Policy list
      tags:
      - Policies
      responses:
        '200':
          description: return policy list
    post:
      summary: Creates a policy
      tags:
      - Policies
      parameters: []
      responses:
        '201':
          description: created policy
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                status:
                  type: string
              required:
              - name
  "/api/policies/update_position":
    parameters:
    - name: Authorization
      in: header
      schema:
        type: string
    post:
      summary: update position
      tags:
      - Policies
      parameters: []
      responses:
        '200':
          description: updated position
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                positions:
                  type: array
  "/api/policies/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    - name: Authorization
      in: header
      schema:
        type: string
    get:
      summary: Retrieves a policy
      tags:
      - Policies
      responses:
        '200':
          description: policy found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
                  status:
                    type: string
        '404':
          description: policy not found
    put:
      summary: Update policy
      tags:
      - Policies
      parameters: []
      responses:
        '200':
          description: updated policy
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                status:
                  type: string
    delete:
      summary: Delete policy
      tags:
      - Policies
      responses:
        '200':
          description: deleted policy
  "/api/policies/{id}/published":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    - name: Authorization
      in: header
      schema:
        type: string
    post:
      summary: Published Policy
      tags:
      - Policies
      parameters: []
      responses:
        '200':
          description: published policy
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
  "/api/policies/{id}/archived":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    - name: Authorization
      in: header
      schema:
        type: string
    post:
      summary: Archived/Unarchived policy
      tags:
      - Policies
      parameters: []
      responses:
        '200':
          description: archived policy
        '422':
          description: can not archived
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                archived:
                  type: boolean
              description: Set true for archived and false for unarchived
  "/api/risks":
    parameters:
    - name: Authorization
      in: header
      schema:
        type: string
    get:
      summary: Risk list
      tags:
      - Risks
      responses:
        '200':
          description: return risk list
    post:
      summary: Creates a risk
      tags:
      - Risks
      parameters: []
      responses:
        '201':
          description: created risk
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                impact:
                  type: string
                likelihood:
                  type: string
                level:
                  type: string
                policy_ids:
                  type: array
              required:
              - name
              - impact
              - likelihood
              - level
  "/api/risks/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    - name: Authorization
      in: header
      schema:
        type: string
    get:
      summary: Retrieves a risk
      tags:
      - Risks
      responses:
        '200':
          description: risk found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  impact:
                    type: string
                  likelihood:
                    type: string
                  level:
                    type: string
        '404':
          description: risk not found
    put:
      summary: Update risk
      tags:
      - Risks
      parameters: []
      responses:
        '200':
          description: updated risk
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                impact:
                  type: string
                likelihood:
                  type: string
                level:
                  type: string
    delete:
      summary: Delete risk
      tags:
      - Risks
      responses:
        '200':
          description: deleted risk
  "/api/exams/{exam_id}/share_exams":
    parameters:
    - name: exam_id
      in: path
      required: true
      schema:
        type: integer
    - name: Authorization
      in: header
      schema:
        type: string
    get:
      summary: Share Exam list
      tags:
      - Share Exams
      responses:
        '200':
          description: return share exam list
    post:
      summary: Creates a share exam
      tags:
      - Share Exams
      parameters: []
      responses:
        '201':
          description: created share exam
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                invited_email:
                  type: string
              required:
              - invited_email
  "/api/exams/{exam_id}/share_exams/{id}":
    parameters:
    - name: exam_id
      in: path
      required: true
      schema:
        type: integer
    - name: id
      in: path
      required: true
      schema:
        type: integer
    - name: Authorization
      in: header
      schema:
        type: string
    delete:
      summary: remove share exam
      tags:
      - Share Exams
      responses:
        '200':
          description: remove share exam
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: ''
