---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/csv":
    post:
      summary: Generate CSV
      tags:
      - CSV
      parameters: []
      responses:
        '201':
          description: csv generated
        '422':
          description: csv generated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                filename:
                  type: string
              required:
              - filename
  "/api/exams":
    get:
      summary: Exam list
      tags:
      - Exams
      responses:
        '200':
          description: return exam list
    post:
      summary: Creates a exam
      tags:
      - Exams
      parameters: []
      responses:
        '201':
          description: created exam
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                starts_on:
                  type: string
                ends_on:
                  type: string
                user_id:
                  type: integer
                updated_by_id:
                  type: integer
              required:
              - name
              - starts_on
              - ends_on
    patch:
      summary: Update Exam
      tags:
      - Exams
      parameters: []
      responses:
        '200':
          description: created exam
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                starts_on:
                  type: string
                ends_on:
                  type: string
                user_id:
                  type: integer
                updated_by_id:
                  type: integer
  "/api/pdf":
    post:
      summary: Generate PDF
      tags:
      - PDF
      parameters: []
      responses:
        '201':
          description: pdf generated
        '422':
          description: error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                filename:
                  type: string
                template:
                  type: string
              required:
              - filename
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: ''
