name: Deploy Demo

on:
  push:
    branches:
      - demo

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        # tmpfs makes DB faster by using RAM
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RAILS_ENV: test
      GEMFILE_RUBY_VERSION: 3.1.1
      PGHOST: localhost
      PGUSER: postgres

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1
          bundler-cache: false
      - name: Bundle install
        run: bundle
      - name: Create DB
        env:
          RAILS_ENV: test
          ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: ${{secrets.ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY}}
          ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: ${{secrets.ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY}}
          ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: ${{secrets.ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT}}
          DEVISE_JWT_SECRET_KEY: ${{secrets.DEVISE_JWT_SECRET_KEY}}
          OTP_SECRET_KEY: ${{secrets.OTP_SECRET_KEY}}
          POSTGRES_PASSWORD: postgres
        run: |
          bin/rails db:prepare
      - name: Run tests
        env:
          RAILS_ENV: test
          ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: ${{secrets.ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY}}
          ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: ${{secrets.ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY}}
          ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: ${{secrets.ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT}}
          DEVISE_JWT_SECRET_KEY: ${{secrets.DEVISE_JWT_SECRET_KEY}}
          OTP_SECRET_KEY: ${{secrets.OTP_SECRET_KEY}}
          POSTGRES_PASSWORD: postgres
        run: |
          bundle exec rspec
      - name: Rubocop
        run: bundle exec rubocop
      - name: Login to Heroku Container registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Unshallow Clone
        run: git fetch --all --unshallow; git filter-branch -- --all
      - name: Push to heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/complect-v2-demo.git HEAD:master --force
